### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by greyhat94** [Ghost6446/Onlyfans-scrapper#10]
I've tried running the script through VSCode, and I've gotten this error: 

```
Traceback (most recent call last):
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 8.2\Run.py", line 6, in <module>
    from Only.only import Main
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 8.2\Only\only.py", line 21, in <module>
    driver.create(headless = False)
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 8.2\Only\src\util\Driver.py", line 54, in create
    self.driver = webdriver.Chrome(options=self.options,  service=self.service)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\webdriver.py", line 218, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__      
    super().__init__(
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__    
    super().__init__(
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__     
    self.start_session(capabilities)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute      
    self.error_handler.check_response(response)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot create default profile directory
Stacktrace:
        GetHandleVerifier [0x00526EE3+174339]
        (No symbol) [0x00450A51]
        (No symbol) [0x00166FF6]
        (No symbol) [0x0018D809]
        (No symbol) [0x0018B3F3]
        (No symbol) [0x00187A0F]
        (No symbol) [0x001BE259]
        (No symbol) [0x001BDBBA]
        (No symbol) [0x001B6DA6]
        (No symbol) [0x00191034]
        (No symbol) [0x00191F8D]
        GetHandleVerifier [0x005C4B1C+820540]
        sqlite3_dbdata_init [0x006853EE+653550]
        sqlite3_dbdata_init [0x00684E09+652041]
        sqlite3_dbdata_init [0x006797CC+605388]
        sqlite3_dbdata_init [0x00685D9B+656027]
        (No symbol) [0x0045FE6C]
        (No symbol) [0x004583B8]
        (No symbol) [0x004584DD]
        (No symbol) [0x00445818]
        BaseThreadInitThunk [0x765D7BA9+25]
        RtlInitializeExceptionChain [0x774DBD2B+107]
        RtlClearBits [0x774DBCAF+191]
        (No symbol) [0x00000000]
```

How can I fix it? Thanks.

**Comment by Ghost6446** [comment]
Install chrome

**Comment by greyhat94** [comment]
I've already installed Chrome.

**Comment by Ghost6446** [comment]
win or linux ?

**Comment by Ghost6446** [comment]
try change this file: https://github.com/Ghost6446/Onlyfans-scrapper/blob/main/Only/src/util/Driver.py
with: 
[Driver.txt](https://github.com/Ghost6446/Onlyfans-scrapper/files/13801799/Driver.txt)
and rename it Driver.py. 

I cant upload .py file

**Comment by greyhat94** [comment]
> win or linux ?

I'm using Windows as OS.

**Comment by greyhat94** [comment]
> try change this file: https://github.com/Ghost6446/Onlyfans-scrapper/blob/main/Only/src/util/Driver.py with: [Driver.txt](https://github.com/Ghost6446/Onlyfans-scrapper/files/13801799/Driver.txt) and rename it Driver.py.
> 
> I cant upload .py file

I've tried replace that file, but, once I run the script, it appears again this message: ```
Traceback (most recent call last):
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 8.2\Run.py", line 6, in <module>
    from Only.only import Main
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 8.2\Only\only.py", line 21, in <module>
    driver.create(headless = False)
  File "C:\Users\umile\Desktop\Tools\OnlyFans Scraper 8.2\Only\src\util\Driver.py", line 55, in create
    self.driver = webdriver.Chrome(options=self.options,  service=self.service)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\webdriver.py", line 218, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__      
    super().__init__(
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__    
    super().__init__(
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__     
    self.start_session(capabilities)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute      
    self.error_handler.check_response(response)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot create default profile directory
Stacktrace:
        GetHandleVerifier [0x00876EE3+174339]
        (No symbol) [0x007A0A51]
        (No symbol) [0x004B6FF6]
        (No symbol) [0x004DD809]
        (No symbol) [0x004DB3F3]
        (No symbol) [0x004D7A0F]
        (No symbol) [0x0050E259]
        (No symbol) [0x0050DBBA]
        (No symbol) [0x00506DA6]
        (No symbol) [0x004E1034]
        (No symbol) [0x004E1F8D]
        GetHandleVerifier [0x00914B1C+820540]
        sqlite3_dbdata_init [0x009D53EE+653550]
        sqlite3_dbdata_init [0x009D4E09+652041]
        sqlite3_dbdata_init [0x009C97CC+605388]
        sqlite3_dbdata_init [0x009D5D9B+656027]
        (No symbol) [0x007AFE6C]
        (No symbol) [0x007A83B8]
        (No symbol) [0x007A84DD]
        (No symbol) [0x00795818]
        BaseThreadInitThunk [0x765D7BA9+25]
        RtlInitializeExceptionChain [0x774DBD2B+107]
        RtlClearBits [0x774DBCAF+191]
```
When running the script, Chrome is already closed. That means it's not running. I don't know why I'm still experiencing this issue. I rely on your help and look forward to hearing from you soon.

**Comment by Ghost6446** [comment]
[Driver.txt](https://github.com/Ghost6446/Onlyfans-scrapper/files/13801850/Driver.txt)

try with this, the problem is that driver cant you, user data folder

**Comment by Ghost6446** [comment]
Maybe different path of chrome

**Comment by greyhat94** [comment]
> Maybe different path of chrome

Happy new year to you! I'm glad to text you again. I tried running your script, and right after that, a Chrome window opened. However, I got this error: 
```
"[11960:9416:0101/174705.857:ERROR:cert_verify_proc_builtin.cc(705)] CertVerifyProcBuiltin for optimizationguide-pa.googleapis.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found".
```

How can I fix it up? Thank you again for your assistance.

**Comment by Ghost6446** [comment]
This is not a error, is debug of seleniumwire

**Comment by greyhat94** [comment]
> This is not a error, is debug of seleniumwire

Ok, thank you for your answer. Once I log in, I need to click on the first option and enter the model's username. After that, the script downloads all the contents to me, right? If, however, I only wanted to download the videos, what should I do?

**Comment by Ghost6446** [comment]
Yes, for the moment just remove all jpg at the end of download file, as soon as i can, i will upload new code with new features a lot faster and without browser, to resolve all of that problem.

**Comment by Ghost6446** [comment]
How i change all.
