### ISSUE TITLE
Application quits with KeyError:'user-agent' error

### ISSUE THREAD

**Issue by dvkrav** [Ghost6446/Onlyfans-scrapper#11]
Hi
I followed the steps in readme till Generator step 

Do you want to auto generare headers file? (With login): y
Have yuo already logged in ?: y
[00:32:13] Close all instance of chrome                             driver.py:20
[00:32:15] LOAD HOME PAGE                                 generate_headers.py:25
Error making request
Traceback (most recent call last):
  File "/Users/user/Library/Python/3.10/lib/python/site-packages/seleniumwire/proxy/proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Users/user/Library/Python/3.10/lib/python/site-packages/seleniumwire/proxy/proxy2.py", line 368, in connect
    super().connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
[00:32:31] Valid api: FIND                                generate_headers.py:30
Traceback (most recent call last):
  File "/Users/user/repos/onlyfans-scraper/Run.py", line 47, in <module>
    main()
  File "/Users/user/repos/onlyfans-scraper/Run.py", line 21, in main
    generate()
  File "/Users/user/repos/onlyfans-scraper/Src/Util/Generator/generate_headers.py", line 35, in generate
    auth_headers[col] = headers[col]
KeyError: 'user-agent'

Any solution to this ?

OS: Mac
Python version: 3.10.10

**Comment by Ghost6446** [comment]
Have you make login before ?
If yes, try increase variable sleep_time in Generator/generate.py, maybe it cant load home page.

**Comment by Ghost6446** [comment]
If i have time i will check the problem

**Comment by Ghost6446** [comment]
Load new version to fix the problem
