### ISSUE TITLE
download fails in the middle

### ISSUE THREAD

**Issue by dvkrav** [Ghost6446/Onlyfans-scrapper#15]
Traceback (most recent call last):
  File "/Users/user/repos/onlyfans-scraper/Run.py", line 53, in <module>
    main()
  File "/Users/user/repos/onlyfans-scraper/Run.py", line 45, in main
    call_api.download_posts()
  File "/Users/user/repos/onlyfans-scraper/Src/Api/api.py", line 93, in download_posts
    self.download_posts(home_api_post.tail_marker)
  File "/Users/user/repos/onlyfans-scraper/Src/Api/api.py", line 93, in download_posts
    self.download_posts(home_api_post.tail_marker)
  File "/Users/user/repos/onlyfans-scraper/Src/Api/api.py", line 93, in download_posts
    self.download_posts(home_api_post.tail_marker)
  [Previous line repeated 3 more times]
  File "/Users/user/repos/onlyfans-scraper/Src/Api/api.py", line 87, in download_posts
    executor.submit(download, url=media.url, path=os.path.join(video_folder_path, str(media.id) + media.get_ext()), headers={"user-agent": get_headers()})
TypeError: can only concatenate str (not "NoneType") to str

**Comment by Ghost6446** [comment]
Name of creator ?

**Comment by dvkrav** [comment]
kaliroses

**Comment by Ghost6446** [comment]
I dont have money to test it, there is other creator with the same problem (witth free subscription, so i can test) ?

**Comment by dvkrav** [comment]
you can try studiostassi

**Comment by Ghost6446** [comment]
Today i will upload the fix

**Comment by Ghost6446** [comment]
Now is fix
