### ISSUE TITLE
unknow error

### ISSUE THREAD

**Issue by Erikusan1707** [Ghost6446/Onlyfans-scrapper#6]
hello there, 
well i have an error that occurs only on one profil so far  and i don't know python programation so if someone could help me to understand or need some precision . i have the 0.7.1 version
Traceback (most recent call last):
  File "f:\Onlyfans-scrapper-main\Run.py", line 4, in <module>
    on.get_all_media()
  File "f:\Onlyfans-scrapper-main\Only\only.py", line 340, in get_all_media
    download(
  File "f:\Onlyfans-scrapper-main\Only\only.py", line 94, in download
    dump_post(radice = succ_req['data']['list'])
  File "f:\Onlyfans-scrapper-main\Only\util\api.py", line 35, in dump_post
    for j in range(len(radice[i]['media'])):
                       ~~~~~~~~~^^^^^^^^^
KeyError: 'media'

**Comment by Erikusan1707** [comment]
Hi
The name is xofreja
And there's at least 1000 médias on it
Thanks for the answer

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ghost6446** [comment]
I try getting only last media and work, now i try all media i think is too much.
